### ISSUE TITLE
Low success rate

### ISSUE THREAD

**Issue by wenjinzhang** [hkthirano/targeted_UAP_CIFAR10#1]
Hi,

Thank you for sharing your project. I tried to run ```generate_noise.py``` with the default configuration. I got a 9.1% attack success rate. Would you please share with me the configuration with a high success rate as you have shown in the readme?

![image](https://user-images.githubusercontent.com/44008219/181592238-0f3e6d76-9213-4805-9a71-c12dbdfc080d.png)

Thanks

**Comment by kztakemoto** [comment]
Thanks. Pls correct line 35 in `generate_noise.py` as follows:
```
num_each_class = 10
==> num_each_class = 1000
```

**Comment by kztakemoto** [comment]
Thanks. Pls correct line 35 in `generate_noise.py` as follows:
```
num_each_class = 10
==> num_each_class = 1000
```
